# -*- coding: utf-8 -*-
"""SkillNavigator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YSW0UFsl5rtA8LAxUYmqF3YW01Qggd2
"""

!pip install fastapi uvicorn groq python-dotenv pyngrok

"""# Backend Code"""

import os
import json
import asyncio
import uvicorn
from fastapi import FastAPI
from pydantic import BaseModel
from groq import Groq
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv

# 1. LOAD ENVIRONMENT VARIABLES FROM .env
load_dotenv()
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# Initialize Client
client = Groq(api_key=GROQ_API_KEY)
app = FastAPI()

# 2. CORS MIDDLEWARE (Important for Flutter Web Loading)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class UserProfile(BaseModel):
    field: str
    experience: str

@app.post("/generate-roadmap")
async def generate_roadmap(profile: UserProfile):
    prompt = f"""
    Create a 30-day career roadmap for a {profile.experience} in {profile.field} in Pakistan.
    Return ONLY a JSON object with a key "roadmap" containing a list of 30 objects.
    Each object must have: "day", "topic", "task", "resource".
    Do not include any text before or after the JSON.
    """

    completion = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}],
        response_format={"type": "json_object"}
    )

    return json.loads(completion.choices[0].message.content)

@app.get("/")
def home():
    return {"status": "SkillNavigator Backend is Live with Secure Env!"}

# Running in Colab
if __name__ == "__main__":
    config = uvicorn.Config(app, host="0.0.0.0", port=8000)
    server = uvicorn.Server(config)
    # Get or create the event loop correctly
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

    loop.create_task(server.serve())

# 1. Install Localtunnel
!npm install -g localtunnel

# 2. Get your Colab IP address (you will need this for the "Tunnel Password")
import urllib
print("Your Password (IP Address) is:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())

# 3. Start the tunnel in the background
# Make sure your FastAPI is running on port 8000 first!
get_ipython().system_raw('lt --port 8000 >> url.txt 2>&1 &')

# 4. Wait a second and then print your URL
import time
time.sleep(2)
with open('url.txt', 'r') as f:
    print("\n🚀 YOUR PUBLIC API URL:", f.read())